"""update_game_3

Revision ID: d3a3eafe1aa3
Revises: 23fa58001867
Create Date: 2018-10-03 14:01:05.582017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a3eafe1aa3'
down_revision = '23fa58001867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sp_games', sa.Column('next_day_time', sa.Integer(), nullable=True))
    op.add_column('sp_games', sa.Column('team_victory_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sp_games', 'team_victory_points')
    op.drop_column('sp_games', 'next_day_time')
    # ### end Alembic commands ###
